---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customers-v1
  namespace: apis
spec:
  apiName: customers
  release: 1.0.0
  routes:
    - pathPrefix: "/v1"
  stripPathPrefix: false  
  service:
    name: customer-app-v1
    openApiSpec:
      path: /openapi.yaml
      port:
        number: 3000
    port:
      number: 3000
  title: v1