---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customers-v1
  namespace: apis
spec:
  apiName: customers
  headers:
    request: {}
    response: {}
  release: v1.0.0
  routes:
    - pathPrefix: /v1
  service:
    name: customer-app-v1
    openApiSpec:
      path: /openapi.yaml
      port:
        number: 3000
    port:
      number: 3000
  stripPathPrefix: true
  title: v1