---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customers-v1
  namespace: apis
spec:
  apiName: test
  headers:
    request: {}
    response: {}
  release: v1.0.0
  routes:
  - headers:
      version: v1
  service:
    name: customer-app-v1
    openApiSpec:
      path: /openapi.yaml
      port:
        name: ""
        number: 3000
    port:
      name: ""
      number: 3000
  stripPathPrefix: false
  title: v1