apiVersion: hub.traefik.io/v1alpha1
kind: APIRateLimit
metadata:
  name: my-rate-limit-fte

spec:
  limit: 100
  period: 1m

  groups:
    - support

  apiSelector:
    matchExpressions:
      - key: area
        operator: In
        values:
          - flights
          - tickets
          - employee