---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customers
  namespace: apis
  labels:
    area: customers
    module: crm  
spec:
  currentVersion: customers-v2
  pathPrefix: /customers