---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customers-v2
  namespace: apis
spec:
  apiName: customers
  release: 2.0.0
  routes:
    - pathPrefix: "/v2"
  service:
    name: customer-app-v2
    openApiSpec:
      path: /openapi.yaml
      port:
        number: 3000
    port:
      number: 3000
  stripPathPrefix: false
  title: v2