---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app-v2
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app-v2
  template:
    metadata:
      labels:
        app: customer-app-v2
    spec:
      containers:
        - name: api
          image: immanuelfodor/json-server:latest
          args: ["--watch", "/api/api.json", "--static", "/public"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
      volumes:
        - name: api-data
          configMap:
            name: customer-data
        - name: openapi
          configMap:
            name: customer-v2-apispec

---
apiVersion: v1
kind: Service
metadata:
  name: customer-app-v2
  namespace: apis
  labels:
    app: customer-app-v2
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: customer-app-v2

