---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-data
  namespace: apis
data:
  api.json: |
    {
      "customers": [
        { "id": 1, "firstName": "John", "lastName": "Doe", "points": 100, "status": "bronze" },
        { "id": 2, "firstName": "Jane", "lastName": "Doe", "points": 200, "status": "silver" },
        { "id": 3, "firstName": "John", "lastName": "Smith", "points": 300, "status": "gold" }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app-v2
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: api
          image: immanuelfodor/json-server:latest
          args: ["--watch", "/api/api.json", "--static", "/public"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
      volumes:
        - name: api-data
          configMap:
            name: customer-data
        - name: openapi
          configMap:
            name: customer-apispec

---
apiVersion: v1
kind: Service
metadata:
  name: customer-app-v2
  namespace: apis
  labels:
    app: customer-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: customer-app-v2

